### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by staaandup** [Jordhan-Carvalho/d2r-electron#1]
When I first start the game, I get a few reminders about stacking and wards, and then this error appears, and the reminders stop. I never got to the bounty runes reminder because this error always appears.

![2022-11-27 19_13_30-Error](https://user-images.githubusercontent.com/50317210/204152965-14812be3-507a-433d-8dae-cf210417132c.png)

What could be causing this?
I'm using an old Windows 10 build 10240.

**Comment by Jordhan-Carvalho** [comment]
Will check it out first thing tomorrow.

Does it happen every game? If so, could you tell the ingame time when it happens?

**Comment by staaandup** [comment]
I was just spectating a game for a few minutes, and near the end of minute 15 it reminded me of stacking creeps, but at minute 16 it didn't say anything about mid runes, so I minimized the game, and the same error reappeared, perhaps slightly different this time?

![2022-11-28 02_12_46-Error](https://user-images.githubusercontent.com/50317210/204180399-35861baa-f256-4468-9618-a7ffbab71ab8.png)

Anyway, I realized that by clicking OK and continuing to watch the game, the reminders kept working, so I just wrote an autohotkey script that checks for this error window and kills it; it's not an ideal solution, but as long as the reminders keep working, I don't mind ;D

The only other issue I'm having is that the app does not save my reminder and delay settings. I have to enter them again every time I exit and restart it.

I also have a suggestion.

-I'm not sure if this is possible, but if only for the first 5 or 6 minutes of the game, 10 seconds before the minute ends, it reminds me to body block the enemy small camp and 10 seconds later, it reminds me to pull the hard camp (I play offlane/pos 4 a lot and this would be very useful to have)

**Comment by Jordhan-Carvalho** [comment]
It seems that sometimes the dota gsi sends a fault json... I solved this by implementing an error handling for this case.

I'm working on the auto-update feature, so it's easier for everyone to get the new fixes/features. After that, I will start working on the persistence side of things (will keep your configurations saved).

Will post here when I finish the auto-update

**Comment by staaandup** [comment]
@Jordhan-Carvalho I tried v1.0.1, and while it doesn't generate any error windows, the reminders still stop working at some point in the game, and because there is no error window to skip or click OK on, the reminders will remain dysfunctional until the app is restarted. So the errors remain, but they are hidden and cannot be bypassed?

**Comment by Jordhan-Carvalho** [comment]
I'm failing to reproduce the bug... can you paste you .cfg file?

Anyway I have added logs to help figure it out, after you update the app and the bug occurs you should find the logs located in
```%USERPROFILE%\AppData\Roaming\d2r-electron\logs\```
Then send me them, here or on your discord server.

On the last release v1.1.1 the auto-update is working, could you download the app one last time?
https://d2r-electron-server-release.vercel.app/
or download the .exe from the releases page

**Comment by Jordhan-Carvalho** [comment]
> The only other issue I'm having is that the app does not save my reminder and delay settings. I have to enter them again every time I exit and restart it.

Just fyi, v.1.2.0 is available with persistent configuration, if you have already downloaded the v1.1.1 it will auto-update

**Comment by staaandup** [comment]
@Jordhan-Carvalho The reminders in v1.1.1 stop very late in the game, like after 50 minutes of gameplay, I played two long games and did not hear the (neutral tier5 items are available) reminder in either of them.

Here is the main.log
[main.log](https://github.com/Jordhan-Carvalho/d2r-electron/files/10134132/main.log)

v1.1.1, This error message appears when the app attempts to update itself.
![2022-12-01 16_52_53-Error](https://user-images.githubusercontent.com/50317210/205104955-68633066-435b-46cf-b153-1061d3149d77.png)

But the update is still successful?
![2022-12-01 17_03_55-d2r_electron](https://user-images.githubusercontent.com/50317210/205104988-cead86be-9fb4-4523-bc41-a7ce1c00b96a.png)

I haven't played with v1.2.0 yet, but it does save my settings :')

**Comment by Jordhan-Carvalho** [comment]
The log was really helpful, it appears that sometimes the game sends a really big payload and the function was adding an extra character "," on it when the bytes exceeded an array slot.
This should be fixed now.

For the update error, it was a simple forgotten import... you will probably get it again one last time when auto-updating from 1.2.0 to v1.2.1... you can just close the error and reopen the app, it will be updated to 1.2.1.

**Comment by staaandup** [comment]
@Jordhan-Carvalho Thank you so much for all of the fixes! I'm using v1.2.1, and everything appears to be working perfectly. I'm looking forward to more app features and updates <3.

**Comment by Jordhan-Carvalho** [comment]
You're welcome!
I just released the v1.3.0 update with 3 new reminders, tower deny, day/night, and a Roshan/aegis timer.

As the bugs on this issue seem to be solved, I will close this one. But do not hesitate to open a new one if you encounter any new bugs or suggestion
