### ISSUE TITLE
Three thoughts on the app

### ISSUE THREAD

**Issue by staaandup** [Jordhan-Carvalho/d2r-electron#13]
1. I keep thinking about the roshan timer every time I have to minimize the game and write the time and click activate,and if you play on full screen like me, it's just too much. I have this idea if it's possible to implement, when roshan dies you press a combination of keys like LCtrl+Lalt+R and the App will copy the game time to itself and start the roshan and aegis timers, do you think it's possible?

2. When the app updates itself, it uses a lot of internet and then a lot of disk space, and if an update occurs during a crucial point in the game, it can be disastrous for me. I believe I was disconnected from the game as a result of this, so I have a problem with it, but many others who use newer hardware will most likely not notice.
What I'd like to see is an option to turn on or off updates while Dota 2 is running, and if that's too much work, perhaps on or off for automatic updates in general. and a button to manually update when I'm done for the day.

![2022-12-05 20_23_06-Task Manager](https://user-images.githubusercontent.com/50317210/205736087-28de9859-c974-4612-af6b-390b60dedb52.png)

3. I play Dota on full screen, and whenever the app finishes updating itself, this window shows up, and if it shows up during a Dota match, it minimizes the game for me, so I'm wondering if it's possible to make this window have a lower priority or something than all other windows, so it doesn't interrupt me during the game.

![2022-12-05 20_23_30-Dota 2 Reminders Update](https://user-images.githubusercontent.com/50317210/205736143-a5f6c025-ed2d-4426-8fd9-d2c56d9c3d8a.png)

**Comment by Jordhan-Carvalho** [comment]
The updates will now only happen when the game is not running, so the point 2 and 3 should be fixed.

For the roshan I have add it to the roadmap for a future release
